게시물 상세 내용 확인, 댓글 기능 구현
Team-Carea/Carea-Server pull request #21
Opened 2024-02-12 13:42 UTC by naneunimjee

## 📍 Issue 번호
#11 

## 🛠️ PR 세부 내용
1. HTML을 render했던 코드를 모두 JSON을 리턴하도록 수정
2. url에 post_id가 있으면 그 post_id에 해당하는 게시물의 상세정보를 출력
3. GET과 POST의 여부에 따라 댓글 출력, 댓글 작성 기능 구현

2024-02-15 07:00 UTC, ilu25 commented on carea/carea/settings.py
> +    'rest_framework'
위에 comments, rest_framework 이미 있어서 삭제 필요

2024-02-15 07:51 UTC, ilu25 requested changes
코드 리뷰한 거 확인 부탁!

2024-02-15 07:51 UTC, ilu25 commented on carea/carea/settings.py
> +AUTH_USER_MODEL = 'users.User'
해당 코드도 위에 이미 존재하므로 삭제 필요

2024-02-15 07:51 UTC, ilu25 commented on carea/comments/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
중복된 필드 삭제 필요

2024-02-15 07:51 UTC, ilu25 commented on carea/posts/models.py
> +    # foreign key는 다 자동으로 뒤에 _id 붙여줘서 뺌
저번에 디코에 남길 때 필요했던 주석이라 삭제해도 될 듯!

2024-02-15 07:51 UTC, ilu25 commented on carea/comments/serializers.py
> +from django.shortcuts import get_object_or_404
이 import문은 안 쓰이는 것 같은데 맞나유? 안 쓰이는 거면 삭제해도 될 듯!

2024-02-15 07:51 UTC, ilu25 commented on carea/posts/urls.py
> +    path('<int:post_id>/comment/', include('comments.urls')),
url에 있는 comment -> comments로 변경 가능할까유 
(보통 url에 복수형으로 많이 써서 통일하는 게 좋을 듯!)

2024-02-15 07:51 UTC, ilu25 commented on carea/posts/templates/post_detail.html
이 파일은 어디에 쓰이는 거야?

2024-02-16 05:48 UTC, naneunimjee commented on carea/posts/templates/post_detail.html
이건 이전에 html로 구현했었을 때 만들었던 포스트 상세보기 html입니당

2024-02-16 06:46 UTC, merged